import React from "react";
import { LineChart, Line, XAxis, YAxis, Tooltip, Rectangle } from "recharts";

/**
 * Component DuréeG
 * @param {dureeData} dureeData is generated by the Data function and its endpoint in order to retrieve the relevant data  from the api
 * DuréeG shows the average session duration in the form of a LineChart. The x-axis corresponds to the average session duration. A tooltip appears on the fly.
 */

const DuréeG = (dureeData) => {
  /**
   * Mocked Data from backend endPoints : http://localhost:3000/user/${userId}/average-sessions
   */
  let mock = dureeData.data?.sessions;

  /** Function CustomTooltip
   * function for shaping the Tooltip
   */
  function CustomTooltip({ active, payload }) {
    if (active) {
      return (
        <div className="tooltipDureeG">
          <p>{payload[0].value} min </p>
        </div>
      );
    }
  }

  const CustomCursor = (props) => {
    const { points, width } = props;
    const { x, y } = points[0];

    return (
      <Rectangle
        fill="#000000"
        fillOpacity={0.1}
        x={x}
        y={y}
        width={width}
        height={463}
      />
    );
  };

  return (
    <div className="containerDuree">
      <h1 className="containerDuree__title">
        Durée moyenne des <br />
        sessions
      </h1>
      <LineChart
        className="containerDuree__graph"
        width={369}
        height={268}
        data={mock}
        style={{ backgroundColor: "red" }}
      >
        <XAxis dataKey="day" width={"100%"} visibility={"hidden"} />
        <YAxis visibility={"hidden"} domain={[15, 100]} />
        <Tooltip
          content={<CustomTooltip />}
          wrapperStyle={{ outline: "none" }}
          cursor={<CustomCursor />}
        />
        <Line
          type="monotone"
          dataKey="sessionLength"
          stroke="white"
          strokeWidth={2}
          dot={false}
        />
      </LineChart>
      <div className="containerDuree__week">
        <p>L</p>
        <p>M</p>
        <p>M</p>
        <p>J</p>
        <p>V</p>
        <p>S</p>
        <p>D</p>
      </div>
    </div>
  );
};

export default DuréeG;
