import React from "react";

/**
 * Component HeaderMain
 * @param {props} props props is generated by the Data function and its endpoint in order to retrieve the relevant data   from the api
 * HeaderMain allows you to dynamically display the name of the selected user
 */

const HeaderMain = (props) => {
  /**
   * Mocked Data from backend endPoints : http://localhost:3000/user/${userId}
   */
  let mock = props.data;
  return (
    <div className="main__title">
      <h1 className="main__title--h1">
        Bonjour{" "}
        <span className="main__title--h1--name">
          {mock?.userInfos.firstName}
        </span>
      </h1>
      <p className="main__title--comment">
        Félicitation ! Vous avez explosé vos objectifs hier 👏
      </p>
    </div>
  );
};

export default HeaderMain;
