import React from "react";
import { RadialBarChart, RadialBar, PolarAngleAxis } from "recharts";

/**
 * Component Score
 * @param {scoreData} scoreData is generated by the Data function and its endpoint in order to retrieve the relevant data  from the api
 * Score Enables Score data in % to be retrieved and displayed in graphical form(RadialBarChart), Width Recharts library
 */

const Score = (scoreData) => {
  let valuePourcentage;
  let result;
  /**
   * Mocked Data from backend endPoints : http://localhost:3000/user/${userId}
   */
  const mock = scoreData?.data;

  /**
   * Is used to verify that it is the key of the object, and to multiply it by 100 in order
   * to find the percentage to display in RadialBarChart
   */

  if (scoreData.data === undefined) {
  } else {
    if (mock?.todayScore) {
      valuePourcentage = [{ value: mock?.todayScore * 100 }];
      result = mock?.todayScore * 100;
    } else {
      valuePourcentage = [{ value: mock?.score * 100 }];
      result = mock?.score * 100;
    }

    return (
      <RadialBarChart
        width={258}
        height={263}
        innerRadius="70%"
        outerRadius="80%"
        startAngle={170}
        endAngle={360 + 170}
        barSize={12}
        data={valuePourcentage}
        style={{ backgroundColor: "#FBFBFB" }}
      >
        <PolarAngleAxis
          type="number"
          domain={[0, 100]}
          angleAxisId={0}
          tick={false}
        />
        <RadialBar
          cornerRadius={30 / 2}
          dataKey="value"
          fill="#FF0000"
          // background={{ fill: "#295049" }}
        />
        <text
          x="50%"
          y="45%"
          fill="#282D30"
          textAnchor="middle"
          dominantBaseline="central"
        >
          <tspan fontSize="26" fontWeight={700}>
            {result}%
          </tspan>
        </text>
        <text
          x="50%"
          y="55%"
          fill="#74798C"
          textAnchor="middle"
          dominantBaseline="central"
        >
          <tspan fontSize="16" fontWeight={500}>
            de votre objectif
          </tspan>
        </text>
        <text
          x="15%"
          y="15%"
          fill="#282D30"
          textAnchor="middle"
          dominantBaseline="central"
        >
          <tspan fontSize="15" fontWeight={500}>
            Score
          </tspan>
        </text>
      </RadialBarChart>
    );
  }
};

export default Score;
